### ISSUE TITLE
wrong origin of putImageData

### ISSUE THREAD

**Issue by default-student** [Eric-Canas/Homography.js#7]
https://github.com/Eric-Canas/Homography.js/blob/87c733e78ca0d2d5b8bf0321fafec8192725b707/README.md?plain=1#L134

here you use math.min to determine if the topleft corner should define the origin of the warp pic or if the x or y coordinat of another corner should be used. this is needed for when the origin of the drawing of the picture is moved inward. if the upper left corner is moved this origin for drawing with ctx.putImageData is now wrong and for x the x of the bottomleft and for y the y of the topright has to be used.

i implemented it as follows:
`ctx.putImageData(resultImage, Math.min(dstPoints[0][0], dstPoints[1][0]), Math.min(dstPoints[0][1], dstPoints[2][1]));`

**Comment by Eric-Canas** [comment]
Hi! 

I tried to do it that way. 

Results are different. The one I put on the readme rotates over itself, while that other one produce a rotation over a larger horizontal space. 

If that's what you are looking for, that implementation is completely valid

**Comment by default-student** [comment]
im using your code to transform an image using drag handles on its corners. I think in that case its needed.
Its documented now, so im closing this issue.

P.S.: I need a way to apply the transformation matrix to a single point, is there a way to do that? I cant access the function "getTransformationFunction"

**Comment by default-student** [comment]
> P.S.: I need a way to apply the transformation matrix to a single point, is there a way to do that? I cant access the function "getTransformationFunction"

my case is, that i want to transform not only by the corners of the image but any points on the image
i set these drag points and then move them.
then however doing putimage to the non transformed 

> ctx.putImageData(resultImage, Math.min(dstPoints[0][0], dstPoints[1][0]), Math.min(dstPoints[0][1], dstPoints[2][1]));

doesnt do, as this point gets moved by the transformation
